---
 - hosts: webserver
   remote_user: test
   become: yes
   
   gather_facts: yes
   
   tasks:
      - name: installing httpd package
        yum: name=httpd state=present
      - name: copy index.html file
        copy: src=index.html dest=/var/www/html
      - name: start httpd server
        service: name=httpd state=started


