---

- hosts: webserver
  remote_user: test
  become: yes

  tasks:
     - name: installing httpd package
       yum: name=httpd state=installed
       tags:
          - install 

     - name: copy index.html 
       copy: src=index.html dest=/var/www/html
       tags:
          - copy

     - name: start httpd server
       service: name=httpd state=started
       tags:
          - service 


