---
- hosts: server2.abc.com
  remote_user: test
  become: yes

  tasks: 
     - name: install opejdk
       yum: name=java-1.8.0-openjdk state=installed

     - name: Download Tomcat
       get_url: url=http://mirror.ox.ac.uk/sites/rsync.apache.org/tomcat/tomcat-7/v7.0.93/bin/apache-tomcat-7.0.93.tar.gz dest=/tmp
  
     - name: Create tomcat folder
       file: path=/usr/local/tomcat state=directory

     - name: extract archive
       unarchive: src=/tmp/apache-tomcat-7.0.93.tar.gz  dest=/usr/local/tomcat copy=no

     - name: create tomcat users
       copy: src=/home/test/playbooks/tomcat-users.xml dest=/usr/local/tomcat/apache-tomcat-7.0.93/conf/

     - name: deploy sample.war
       copy: src=sample.war  dest=/usr/local/tomcat/apache-tomcat-7.0.93/webaaps

     - name: start tomcat
       command: nohup /usr/local/tomcat/apache-tomcat-7.0.93/bin/startup.sh &

           
