---

- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
     - name: create a tomcat1 folder at server2.abc.com
       file: path=/home/test/tomcat1 state=directory 
     - name: Download Tomcat
       get_url: url=http://apache.mirror.anlx.net/tomcat/tomcat-7/v7.0.93/bin/apache-tomcat-7.0.93.tar.gz dest=/tmp
     - name: unarchiving to server2.abc.com
       unarchive: src=/tmp/apache-tomcat-7.0.93.tar.gz  dest=/home/test/tomcat1  copy=no
    

